### PR TITLE
Test Enumerable methods with rspec

### PR DESCRIPTION
**Pull request by uwadonat**
Greetings Microverse,
We made all the necessary test cases for testing our previous weeks project of the Enumerable.
We kindly request a review of our efforts.

Bestest regards
Matija and Donat

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :recycle: :red_circle: 
-------------
Hello!! @uwadonat @Mandeln :wave: Great job you did on this project :muscle: :100: 
However, there are a few changes to make to complete this project. :hammer_and_wrench: see them below :eyes: :point_down: 
-------

- [x] Name properly the file where you have your tests. The name must be `testr_spec.rb` instead of `testrspec.rb`. Remember that the files with the RSpec must be named with `_spec.rb` so the specs will run the files with this convention. 
- [x] Check the grammar in your Readme file. Use Grammarly or another app to check the grammar. Having good grammar makes your project more professional. 
-----------------
Make these minor changes above :hammer_and_wrench: :point_up_2: and send it for another review. :muscle: :+1: 
HAPPY CODING!!

**Comment by uwadonat** [comment]
thanks for good comments!
we corrected requested changes ( file name and grammar)

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯
  - [x] All tests are passing 💯
  - [x] Nice job implementing  the previous feedback 💯

- ### To Improve
  - N/A.

_Congratulations on the splendid job **@team** 👍
You can now merge to master and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Comment by uwadonat** [comment]
wau!!! thanks.

**Pull request merged**
